### ISSUE TITLE
MySQL and DateTimeOffset? LockoutEnd

### ISSUE THREAD

**Issue by Quentinb** [linq2db/LinqToDB.Identity#13]
I'm running the identity system against a MySQL DB and get SQL syntax errors for DateTimeOffset. MySQL does not support the datatype.

Found some [related notes](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/79) on the interwebs

**Comment by sdanyliv** [comment]
@Quentinb, please report bugs related to core library in main repository. With samples )
Thanks

**Comment by Quentinb** [comment]
@sdanyliv thanks for the feedback. I have [created one here](https://github.com/linq2db/linq2db/issues/1206)
