### ISSUE TITLE
Upgrade to linq2db version 4.x

### ISSUE THREAD

**Issue by sfadeev** [linq2db/LinqToDB.Identity#24]
Hello!

Is there any plans to upgrade Linq2db.Identity to use linq2db version 4.x?

The library Linq2db.Identity itself works well, but it stops from using newer version of other libraries - linq2db, Npgsql etc.

Upgrade to new version of linq2db is not so hard (couple of methods are changed), but there are some other things that need to pay attention:

1. Syncronize code with actual aspnet core Identity project (https://github.com/dotnet/aspnetcore/tree/main/src/Identity)
2. Update to actual dotnet/c# versions

Thank you!

**Comment by MaceWindu** [comment]
I will release update to support new linq2db version today to unblock updates.

Code synchronization will be a part of next linq2db release alongsize with migration of this project to main repository

**Comment by MaceWindu** [comment]
I've uploaded new version with linq2db 4.4.0 support https://www.nuget.org/packages/linq2db.Identity/3.4.0

This is last legeacy release and next releases will target modern asp.net core

**Comment by sfadeev** [comment]
Everything works now, thanks for the efficiency.
