### ISSUE TITLE
Library isn't compatible with linq2db 5.x

### ISSUE THREAD

**Issue by kekekeks** [linq2db/LinqToDB.Identity#25]
MissingMethodException is thrown somewhere between LinqToDB.Identity  and linq2db.

This prevents Npgsql upgrade since linq2db 4.x isn't compatible with Npgsql 8.x.

**Comment by MaceWindu** [comment]
Man, we really need to migrate this to main repo and release in parallel. Will release fix today

**Comment by MaceWindu** [comment]
@kekekeks, btw, which .net/asp.net version you use in your application?
