### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/LinqToDB.Identity#9]
Shouldn't we increase major version on breaking changes? see : http://semver.org

**Comment by ili** [comment]
Yes from one side... from another they are really tiny and in my mind they are not enough for major release... I'v just removed unnecessary generics... Build will fail but it is 1 minutes to fix.

**Comment by jogibear9988** [comment]
yes, but i think people think that they need to change nothing on a dll replacement when only minor versions were changed...
i think we should change or strategy to only do non breaking changes if we will not increase major version.

**Comment by ili** [comment]
ok, you a right! :)
we'll follow this in next releases.
